version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    build: ./postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sales
      - POSTGRES_USER=iwd
      - POSTGRES_PASSWORD=iwd@2022
  monitoring:
    build: ./dashboard_app
    ports:
      - "8062:8062"
    volumes:
      - ./dashboard_app:/code
    links:
      - "db:mypostgres"
